exclude_dirs:
  - venv
  - .git
  - __pycache__
  - tests
  - src/backend/tests
  - src/frontend/tests
  - src/tradingbot/tests

skips:
  - B404  # Import subprocess warning
  - B603  # subprocess call - check for shell injection
  - B607  # Start process with partial path

per_file_ignores:
  - "**/test_*.py":
      - B101  # Skip assert used warnings in test files
  - "**/tests/**/*.py":
      - B101  # Skip assert used warnings in test files
  - "tests/**/*.py":
      - B101  # Skip assert used warnings in test files
