name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  TEST_POSTGRES_USER: testuser
  TEST_POSTGRES_PASSWORD: testpass
  TEST_POSTGRES_DB: tradingdb_test
  TEST_REDIS_PASSWORD: testpass

jobs:
  test:
    if: false  # Disable test job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test job disabled"

  lint:
    if: false  # Disable lint job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint job disabled"

  security-scan:
    if: false  # Disable security scan job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Security scan job disabled"

  build:
    needs: [test, lint, security-scan]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Trading Bot
        uses: docker/build-push-action@v2
        with:
          context: ./go-migration
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/trading-bot:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/trading-bot:latest

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to staging
        run: |
          cd src/deployment
          ./scripts/deploy.sh staging

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to production
        run: |
          cd src/deployment
          ./scripts/deploy.sh production

  notify:
    needs: [deploy-staging, deploy-production]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
