# Trading Bot Deployment Configuration

version: "1.0"

environment:
  python:
    version: "3.12"
    packages:
      - aiohttp>=3.9.1
      - pandas>=2.2.0
      - pandas_ta>=0.3.14b
      - solana>=0.30.2
      - base58>=2.1.1
      - solders>=0.20.0
      - httpx>=0.26.0
  go:
    version: "1.23.6"
    modules:
      - github.com/gorilla/websocket@v1.5.3
      - github.com/lib/pq@v1.10.9
      - github.com/stretchr/testify@v1.9.0
      - go.uber.org/zap@v1.27.0

services:
  python_backend:
    build:
      context: ./src/tradingbot
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app/src
      - PYTHON_VERSION=3.12
    command: python -m backend.trading_agent.main

  go_backend:
    build:
      context: ./go-migration
      dockerfile: Dockerfile
    environment:
      - GO_VERSION=1.23.6
    command: ./bin/trading

deployment:
  steps:
    - name: "Install Python 3.12"
      command: |
        sudo apt update
        sudo apt install python3.12 python3.12-venv

    - name: "Install Go 1.23.6"
      command: |
        wget https://go.dev/dl/go1.23.6.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -C /usr/local -xzf go1.23.6.linux-amd64.tar.gz

    - name: "Setup Python Environment"
      command: |
        python3.12 -m venv venv
        source venv/bin/activate
        pip install -e src/tradingbot

    - name: "Setup Go Environment"
      command: |
        cd go-migration
        go mod download
        go build -o bin/trading ./cmd/execute_trading

    - name: "Start Services"
      command: |
        # Start Python backend
        cd src/tradingbot
        PYTHONPATH=/app/src python -m backend.trading_agent.main &

        # Start Go backend
        cd go-migration
        ./bin/trading

monitoring:
  metrics:
    - name: "Trading Performance"
      path: "/metrics/trading"
    - name: "System Health"
      path: "/metrics/health"
