global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000', 'backend-canary:8000']
    metrics_path: /metrics

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000', 'frontend-canary:3000']
    metrics_path: /metrics 