version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tradingbot_network

  api_gateway:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - LOCAL_MODEL_ENDPOINT=http://ollama:11434
      - LOCAL_MODEL_NAME=deepseek-1.5b
      - AI_MODEL_MODE=LOCAL
    depends_on:
      - ollama
    networks:
      - tradingbot_network

networks:
  tradingbot_network:
    driver: bridge

volumes:
  ollama_data:
