version: '3.8'

services:
  frontend:
    build:
      context: ../../
      dockerfile: deploy/docker/frontend/Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - api_gateway
    environment:
      - VITE_API_URL=http://api_gateway:8000

  api_gateway:
    build:
      context: ../../
      dockerfile: deploy/docker/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tradingbot
      - REDIS_URL=redis://redis:6379/0

  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradingbot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data:
  grafana_data:
