[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tradingbot-backend"
version = "0.1.0"
description = "Trading Bot Backend Service"
dependencies = []

[tool.setuptools]
packages = ["src.backend"]
