market:
  providers:
    pump:
      base_url: "https://pumpportal.fun/api"
      ws_url: "wss://pumpportal.fun/api/data"
      trade_endpoint: "/trade-local"
      new_tokens_endpoint: "/api/v1/price/list"
      request_timeout: 30s
      reconnect_timeout: 15s
      max_retries: 10
      dial_timeout: 30s
      write_timeout: 30s
      read_timeout: 30s
      pong_wait: 60s
    gmgn:
      base_url: "https://gmgn.ai/defi/router/v1/sol"
      api_key: "${walletkey}"
      use_anti_mev: true
      min_fee: 0.002
      slippage: 0.5
      request_timeout: 30s
      reconnect_timeout: 15s
    solana:
      base_url: "https://api.mainnet-beta.solana.com"
      ws_url: "wss://api.mainnet-beta.solana.com"
      dex_sources: ["serum", "raydium", "orca"]
      timeout: 30s

database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "tradingbot"

server:
  websocket:
    port: 8080
    ping_interval: 15s
    pong_wait: 60s
  grpc:
    port: 50051

trading:
  order:
    commission: 0.001
    slippage: 0.005
    max_order_size: 1000
    min_order_size: 10
  risk:
    max_positions: 5
  engine:
    update_interval: 1s

pricing:
  engine:
    update_interval: 1s
    history_size: 1000
    indicators: ["ema", "rsi", "macd"]
    min_confidence: 0.7
    max_volatility: 0.2
