risk:
  limits:
    max_position_size: 1000.0
    max_drawdown: 0.15
    max_daily_loss: 500.0
    min_margin_level: 1.5
  
  profit_taking:
    - multiplier: 2.0
      percentage: 0.20
    - multiplier: 3.0
      percentage: 0.25
    - multiplier: 5.0
      percentage: 0.20
  
  entry_thresholds:
    max_market_cap: 30000.0
    min_volume: 1000.0
    min_liquidity: 5000.0
  
  technical:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    moving_averages:
      short_period: 30
      long_period: 60
      crossover_confirmation: 2

  monitoring:
    price_update_interval: 30
    position_check_interval: 60
    risk_check_interval: 300
