site_name: Trading Bot API
site_description: Documentation for the Trading Bot API
site_author: Trading Bot Team
repo_url: https://github.com/yourusername/tradingbot
repo_name: tradingbot

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_category_heading: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Quick Start: getting-started/quickstart.md
  - API Reference:
    - Market Analysis: api/market.md
    - Risk Management: api/risk.md
    - Trading: api/trading.md
    - Monitoring: api/monitoring.md
  - Guides:
    - Authentication: guides/authentication.md
    - Rate Limiting: guides/rate-limiting.md
    - Error Handling: guides/error-handling.md
    - Caching: guides/caching.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Code Style: development/code-style.md
    - Documentation: development/documentation.md
  - Deployment:
    - Docker: deployment/docker.md
    - Kubernetes: deployment/kubernetes.md
    - Monitoring: deployment/monitoring.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/tradingbot
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/yourusername/tradingbot
  version:
    provider: mike 