services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: tradingbot
      POSTGRES_PASSWORD: tradingbot
      POSTGRES_DB: tradingbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflict

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  api_gateway:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://tradingbot:tradingbot@postgres:5432/tradingbot
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3002:80"  # Changed from 3000 to avoid conflict
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api_gateway

volumes:
  postgres_data:
