global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8000']
    metrics_path: '/metrics'

  - job_name: 'trading_agent'
    static_configs:
      - targets: ['trading_agent:8001']
    metrics_path: '/metrics' 